content:
  enabled: true
  content_dataset_path:
    - datasets/ESC-50
    - datasets/urbansound8k
    - datasets/musan
  snr:
    - 0
    - 10
    - 20
gaussian:
  enabled: true
  snr:
    - 0
    - 10
    - 20
gain_transition:
  enabled: true
  min_max_gain_db: 
    - [-40.0,-20.0]
    - [-30.0,-10.0]
    - [-20.0,0.0]
clipping_distortion:
  enabled: true
  max_percentile_threshold: 
    - 20
    - 40
    - 60
impulse_response:
  enabled: true
  ir_path:
    - datasets/EchoThiefImpulseResponseLibrary
  rt60_range:
    - [0.1, 0.5]
    - [0.5, 1.0]
    - [1.0, 1.5]
compression:
  enabled: true
  bit_rate:
    - 8
    - 16
    - 32